
name: Update docker tags
on:
  schedule:
    - cron: '0 5 * * *' # run every 5 hours
  repository_dispatch:
    types: [ update-docker-tags ]

jobs:
  update-docker-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2
      - name: test
        # Debug
        run: |
          git status
      - name: Update-tags
        uses: ./.
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}





